### ISSUE TITLE
failed to spawn command. path: "/usr/bin/qmlls6"

### ISSUE THREAD

**Issue by lkroll** [lkroll/zed-qml#3]
Even though qmlls is installed and available under `/usr/bin/qmlls` the extension tries to launch qmlls6.

**Comment by TooSla** [comment]
Hi, could it be possible to be able to specify path to qmlls through settings? Otherwise it's hard to get it going with current hard-coded path on macOS. Same question goes for --build-dir. Thanks!

**Comment by TooSla** [comment]
I'd be glad to test or try to add some macos specific implementation bits

**Comment by lkroll** [comment]
You can try out #4 and let me know if it detects qmlls on your system.
If qmlls (or qmlls6) can be found in your $PATH (so for example by using `which qmlls`) then it should work.

**Comment by TooSla** [comment]
sorry but I failed to figure out how to install it. I tried fetching the related branch, built it with "cargo build" and then used Install Dev Extension from Zed but it didn't install for me. But I will try it out once it reaches me through official update or otherwise, maybe you could add some instructions on how to build/install it? Also note that I'm using commercial Qt through their online installer and the qmlls ends up not being in a path, but instead being put at something like /Users/<username>/Qt/6.8.0/macos/bin/qmlls. But I will add it to the path manually when I get to testing this.

**Comment by TooSla** [comment]
just to report back, qmlls is indeed working now as long as it's present in PATH, great! But I do believe it still requires the "--build-dir" to work properly as I'm currently getting all sort of errors from it, e.g: 
- Warnings occurred while importing module "ModuleName": [import]
- Type "MyType" of property "propName" not found. This is likely due to a missing dependency entry or a type not being exposed declaratively. [unresolved-type]

Maybe it would be possible to specify it as an environment variable for now until there is an extension API that will allow to set it with plugin specific preferences?

**Comment by lkroll** [comment]
You are right, I will open a new issue for that.
I haven't really done anything serious in Qt for a while so I will have to look into it.
But I think there is a solution.
By taking a look at the official documentation you can specify the build dir in a file called .qmlls.ini, and you even auto generate it: https://doc.qt.io/qt-6/qtqml-tooling-qmlls.html#configuration-file
